#!/bin/bash
if [ -z "$1" ]; then
  echo "usage: $0 <hostname>"
  exit 1
fi

ssh -o BatchMode\ yes -o StrictHostKeyChecking\ no -l root \
  -q -a -x -i /root/.ssh-sdist/id_rsa -p 1000 $1 /usr/sbin/fai-update-system -v
